"""Reconstructs the gitignored build/ inputs from the released package.

The repo does not contain build/CharacterCreator.data (embedded into the
plugin as IDR_MENU_DATA RCDATA) nor build/Character Creator/ (the 0009/0012
game files + mod.json): both are generated by tools/build_data.py from the
author's private source folders. To rebuild the plugin (e.g. on CI) without
the game, recover them byte-identically from the released zip instead:

  output layout (the Nexus zip, extracted):
    Character Creator/CharacterCreator.asi      the plugin, data embedded
    Character Creator/Character Creator Enhanced/{0009,0012,...}
    Character Creator/mod.json

  recovered:
    build/CharacterCreator.data                 the RCDATA resource (id 101)
    build/Character Creator/{0009,0012,...}
    build/Character Creator/mod.json

Usage: python tools/extract_build_inputs.py [output dir, default ./output]
Only the standard library is used. Run once, then commit build/ with
`git add -f build/` (it stays gitignored otherwise).
"""
import os
import shutil
import struct
import sys

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
RT_RCDATA = 10
IDR_MENU_DATA = 101
MAGIC = b'CCDATA1\x00'


def u16(d, o):
    return struct.unpack_from('<H', d, o)[0]


def u32(d, o):
    return struct.unpack_from('<I', d, o)[0]


def extract_rcdata(dll_path):
    """Raw bytes of the RT_RCDATA / 101 resource of a PE32+ DLL."""
    with open(dll_path, 'rb') as f:
        d = f.read()
    if d[0:2] != b'MZ':
        raise SystemExit(f'{dll_path}: not a PE file')
    pe = u32(d, 0x3C)
    if d[pe:pe + 4] != b'PE\x00\x00':
        raise SystemExit(f'{dll_path}: bad PE signature')
    sections = []
    for i in range(u16(d, pe + 6)):
        o = pe + 24 + u16(d, pe + 20) + i * 40
        vsize, vaddr, rawsize, rawptr = struct.unpack_from('<IIII', d, o + 8)
        sections.append((vaddr, vsize, rawptr, rawsize))

    def to_offset(rva):
        for vaddr, vsize, rawptr, rawsize in sections:
            if vaddr <= rva < vaddr + max(vsize, rawsize) and rva - vaddr < rawsize:
                return rawptr + (rva - vaddr)
        raise SystemExit(f'RVA {rva:#x} not backed by any section')

    is_plus = u16(d, pe + 24) == 0x20B
    directories = pe + 24 + (112 if is_plus else 96)
    res_rva = u32(d, directories + 16)  # directory entry 2 (resource)
    base = to_offset(res_rva)

    def entries(directory):
        total = u16(d, directory + 12) + u16(d, directory + 14)
        return [(u32(d, directory + 16 + i * 8), u32(d, directory + 20 + i * 8))
                for i in range(total)]

    type_dir = next((off for rid, off in entries(base) if rid == RT_RCDATA and off >> 31), None)
    if type_dir is None:
        raise SystemExit('RT_RCDATA not found')
    name_dir = next((off for rid, off in entries(base + (type_dir & 0x7FFFFFFF))
                     if rid == IDR_MENU_DATA and off >> 31), None)
    if name_dir is None:
        raise SystemExit('RCDATA 101 not found')
    for _, off in entries(base + (name_dir & 0x7FFFFFFF)):
        if not off >> 31:  # data entry (any language)
            data_rva, size = struct.unpack_from('<II', d, base + off)
            start = to_offset(data_rva)
            return d[start:start + size]
    raise SystemExit('RCDATA 101 has no data entry')


def describe(blob):
    if not blob.startswith(MAGIC):
        raise SystemExit('extracted data has no CCDATA1 magic')
    end = blob.index(b'\x00', len(MAGIC))
    version = blob[len(MAGIC):end].decode('utf-8', 'replace')
    count = struct.unpack_from('<I', blob, end + 1)[0]
    return version, count


def main():
    reference = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, 'output')
    package = os.path.join(reference, 'Character Creator')
    asi = os.path.join(package, 'CharacterCreator.asi')
    for path in (asi, os.path.join(package, 'Character Creator Enhanced'), os.path.join(package, 'mod.json')):
        if not os.path.exists(path):
            raise SystemExit(f'missing {path} - extract the Nexus zip under {reference}/ first')

    blob = extract_rcdata(asi)
    version, count = describe(blob)
    build = os.path.join(ROOT, 'build')
    os.makedirs(build, exist_ok=True)
    with open(os.path.join(build, 'CharacterCreator.data'), 'wb') as f:
        f.write(blob)
    print(f'data: version {version}, {count} files, {len(blob)} bytes')

    game_out = os.path.join(build, 'Character Creator')
    if os.path.exists(game_out):
        shutil.rmtree(game_out)
    shutil.copytree(os.path.join(package, 'Character Creator Enhanced'), game_out)
    shutil.copy2(os.path.join(package, 'mod.json'), os.path.join(game_out, 'mod.json'))
    total = sum(os.path.getsize(os.path.join(d, f)) for d, _, fs in os.walk(game_out) for f in fs)
    print(f'game files: {game_out} ({total} bytes)')


if __name__ == '__main__':
    main()
